object Dependencies {
    private const val dotEnvVersion = "5.1.0"
    private const val junitVersion = "5.5.+"
    const val kotlinVersion = "1.3.40"
    private const val plantUmlVersion = "1.2019.8"
    private const val slf4jVersion = "1.7.26"
    private const val structurizrVersion = "1.2.0"

    const val dotEnv = "io.github.cdimascio:java-dotenv:$dotEnvVersion"
    const val junitApi = "org.junit.jupiter:junit-jupiter-api:$junitVersion"
    const val junitEngine = "org.junit.jupiter:junit-jupiter-engine:$junitVersion"
    const val plantUml = "net.sourceforge.plantuml:plantuml:$plantUmlVersion"
    const val slf4jLog4j = "org.slf4j:slf4j-log4j12:$slf4jVersion"
    const val structurizrAdrTools = "com.structurizr:structurizr-adr-tools:$structurizrVersion"
    const val structurizrAnnotations = "com.structurizr:structurizr-annotations:$structurizrVersion"
    const val structurizrClient = "com.structurizr:structurizr-client:$structurizrVersion"
    const val structurizrCore = "com.structurizr:structurizr-core:$structurizrVersion"
    const val structurizrPlantUml = "com.structurizr:structurizr-plantuml:$structurizrVersion"
    const val structurizrSpring = "com.structurizr:structurizr-spring:$structurizrVersion"
}