object Dependencies {
    const val dokkaVersion = "0.9.18"
    private const val dotEnvVersion = "5.2.1"
    private const val junitVersion = "5.6.2"
    const val kotlinVersion = "1.4.0"
    const val ktlintVersion = "9.3.0"
    private const val plantUmlVersion = "1.2020.15"
    private const val slf4jVersion = "1.7.30"
    private const val structurizrVersion = "1.5.0"
    private const val structurizrAdrToolsVersion = "1.3.6"
    private const val structurizrAnnotationsVersion = "1.3.5"
    private const val structurizrPlantUmlVersion = "1.5.0"
    private const val structurizrSpringVersion = "1.3.5"

    const val dotEnv = "io.github.cdimascio:java-dotenv:$dotEnvVersion"
    const val junitApi = "org.junit.jupiter:junit-jupiter-api:$junitVersion"
    const val junitEngine = "org.junit.jupiter:junit-jupiter-engine:$junitVersion"
    const val plantUml = "net.sourceforge.plantuml:plantuml:$plantUmlVersion"
    const val slf4jLog4j = "org.slf4j:slf4j-log4j12:$slf4jVersion"
    const val structurizrAdrTools = "com.structurizr:structurizr-adr-tools:$structurizrAdrToolsVersion"
    const val structurizrAnnotations = "com.structurizr:structurizr-annotations:$structurizrAnnotationsVersion"
    const val structurizrClient = "com.structurizr:structurizr-client:$structurizrVersion"
    const val structurizrCore = "com.structurizr:structurizr-core:$structurizrVersion"
    const val structurizrPlantUml = "com.structurizr:structurizr-plantuml:$structurizrPlantUmlVersion"
    const val structurizrSpring = "com.structurizr:structurizr-spring:$structurizrSpringVersion"
}
